### ISSUE TITLE
Update All Existing Toast Usages to Leverage New Toast System

### ISSUE THREAD

**Issue by mahid797** [bluewave-labs/bluewave-dataroom#114]
# Refactor Existing Toast Usages to Use ToastProvider

### **Description**  
The toast notification system has been refactored to use a centralized `ToastProvider`, simplifying toast management and improving scalability. This issue involves updating all existing toast usages in the codebase to adopt the new `ToastProvider` system.

Previously, each toast required manual JSX insertion and state management using `useToast`. With the new implementation, developers can simply call `showToast` to dynamically render notifications.

This task is primarily focused on ensuring all components and pages are updated to use the new toast system and thoroughly tested for consistent behaviour.

---

### **Key Tasks**  
1. **Identify All Existing Toast Usages**:  
   Locate every component or page that uses the `useToast` hook and `<Toast>` component.
   
2. **Refactor Usage**:  
   Replace the old implementation with the new `showToast` function from the `useToast` hook. Remove redundant `<Toast>` components from JSX.

3. **Test Toast Behavior**:  
   Verify that all toasts are rendered correctly with the intended message, variant, and behavior.

---

## Tasks  
- [x] Search for existing instances of `useToast` and `<Toast>` components in the codebase.  
- [x] Refactor each instance to use the new `showToast` function.  
- [x] Remove redundant `<Toast>` components from the JSX.  
- [x] Test the updated code to ensure toasts are working as expected.  

---

### **Sample Usage**  
Below is an example of how the new `useToast` hook and `showToast` function should be used:

#### **Old Implementation**
```tsx
const photoDeleteToast = useToast();
<Toast
  message="Photo Deleted!"
  open={photoDeleteToast.open}
  hideToast={photoDeleteToast.hideToast}
  variant="error"
/>;
```

#### **Updated Implementation**
```tsx
const { showToast } = useToast();
const handleDeletePhoto = () => {
  showToast({
    message: 'Photo Deleted!',
    variant: 'error',
  });
};
```

---

### **Expected Outcome**  
1. **Consistent Usage**:  
   All toast notifications across the app leverage the `ToastProvider`.  
2. **Improved Codebase**:  
   Reduces redundancy and simplifies notification management.  
3. **Thorough Testing**:  
   Ensures all notifications behave as intended.
