### ISSUE TITLE
Authentication Backend Fixes

### ISSUE THREAD

**Issue by mahid797** [bluewave-labs/bluewave-dataroom#92]
#### Tasks:
- [x] **Review Master Branch**
  - Ensure the latest version of the master branch is pulled and up-to-date before starting on the tasks below and in #93.
- [x] **Fix Sign-In and Log-Out Flickering Issue**
  - Resolve the flickering that occurs on the Sign-In and Log-Out pages.
- [x] **Remove Placeholder Authentication UI**
  - Delete any placeholder Auth UI pages and folders to clean up the codebase.
- [x] **Update User Schema**
  - [x] Add fields for First Name and Last Name.
  - [x] Set default User role to "Admin".
---

**Comment by SajanGhuman** [comment]
All issues are fixed
